In [1]:
import pandas as pd

y = pd.Period('2016')
y

Period('2016', 'Y-DEC')

In [3]:
y.start_time

Timestamp('2016-01-01 00:00:00')

In [5]:
y.end_time

Timestamp('2016-12-31 23:59:59.999999999')

In [11]:
m = pd.Period('2024-3', freq = 'M')
m

Period('2024-03', 'M')

In [7]:
m.start_time

Timestamp('2011-01-01 00:00:00')

In [8]:
m.end_time

Timestamp('2011-01-31 23:59:59.999999999')

In [15]:
m + 1

Period('2024-04', 'M')

In [25]:
h = pd.Period('2016-02-28 23:00:00', freq = 'H')
h

C:\Users\Smoke Nandos\AppData\Local\Temp\ipykernel_12720\242320126.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  h = pd.Period('2016-02-28 23:00:00', freq = 'H')

Period('2016-02-28 23:00', 'h')

In [ ]:
# d + 1

Period('2016-02-29', 'D')

In [26]:
h.start_time

Timestamp('2016-02-28 23:00:00')

In [27]:
h.end_time

Timestamp('2016-02-28 23:59:59.999999999')

In [33]:
h - 6

Period('2016-02-28 17:00', 'h')

In [34]:
h + pd.offsets.Hour(400)

Period('2016-03-16 15:00', 'h')

In [37]:
q = pd.Period('2017Q1', freq = 'Q-JAN')
q

Period('2017Q1', 'Q-JAN')

In [38]:
q.start_time

Timestamp('2016-02-01 00:00:00')

In [39]:
q.end_time

Timestamp('2016-04-30 23:59:59.999999999')

In [41]:
q.asfreq('M', how = "end")

Period('2016-04', 'M')

In [42]:
q2 = pd.Period('2018Q2', freq = 'Q-JAN')
q2

Period('2018Q2', 'Q-JAN')

In [43]:
q2-q

In [47]:
idx = pd.period_range("2011", periods = 10, freq = 'Q')
idx

PeriodIndex(['2011Q1', '2011Q2', '2011Q3', '2011Q4', '2012Q1', '2012Q2',
             '2012Q3', '2012Q4', '2013Q1', '2013Q2'],
            dtype='period[Q-DEC]')

In [45]:
idx[0].start_time

Timestamp('2011-01-01 00:00:00')

In [46]:
idx[0].end_time

Timestamp('2011-03-31 23:59:59.999999999')

In [48]:
import numpy as np
ps = pd.Series(np.random.randn(len(idx)), idx)
ps

2011Q1    0.457069
2011Q2    1.028336
2011Q3    0.545144
2011Q4   -0.649148
2012Q1    0.034766
2012Q2    0.864830
2012Q3    0.028881
2012Q4    0.222608
2013Q1    0.729600
2013Q2   -0.371061
Freq: Q-DEC, dtype: float64

In [49]:
ps.index

PeriodIndex(['2011Q1', '2011Q2', '2011Q3', '2011Q4', '2012Q1', '2012Q2',
             '2012Q3', '2012Q4', '2013Q1', '2013Q2'],
            dtype='period[Q-DEC]')

In [51]:
pst = ps.to_timestamp()
pst

2011-01-01    0.457069
2011-04-01    1.028336
2011-07-01    0.545144
2011-10-01   -0.649148
2012-01-01    0.034766
2012-04-01    0.864830
2012-07-01    0.028881
2012-10-01    0.222608
2013-01-01    0.729600
2013-04-01   -0.371061
Freq: QS-OCT, dtype: float64

In [52]:
pst.index

DatetimeIndex(['2011-01-01', '2011-04-01', '2011-07-01', '2011-10-01',
               '2012-01-01', '2012-04-01', '2012-07-01', '2012-10-01',
               '2013-01-01', '2013-04-01'],
              dtype='datetime64[ns]', freq='QS-OCT')

In [53]:
pst.to_period()

2011Q1    0.457069
2011Q2    1.028336
2011Q3    0.545144
2011Q4   -0.649148
2012Q1    0.034766
2012Q2    0.864830
2012Q3    0.028881
2012Q4    0.222608
2013Q1    0.729600
2013Q2   -0.371061
Freq: Q-DEC, dtype: float64

In [54]:
import pandas as pd
df = pd.read_csv('wmt.csv')
df

  Line Item  2017Q1  2017Q2  2017Q3  2017Q4  2018Q1
0   Revenue  115904  120854  118179  130936  117542
1  Expenses   86544   89485   87484   97743   87688
2    Profit   29360   31369   30695   33193   29854

In [55]:
df.set_index('Line Item', inplace = True)
df

           2017Q1  2017Q2  2017Q3  2017Q4  2018Q1
Line Item
Revenue    115904  120854  118179  130936  117542
Expenses    86544   89485   87484   97743   87688
Profit      29360   31369   30695   33193   29854

In [56]:
df = df.T 
df

Line Item  Revenue  Expenses  Profit
2017Q1      115904     86544   29360
2017Q2      120854     89485   31369
2017Q3      118179     87484   30695
2017Q4      130936     97743   33193
2018Q1      117542     87688   29854

In [59]:
df.index = pd.PeriodIndex(df.index, freq = 'Q-JAN')
df.index

PeriodIndex(['2017Q1', '2017Q2', '2017Q3', '2017Q4', '2018Q1'], dtype='period[Q-JAN]')

In [60]:
df['Start Date'] = df.index.map(lambda x: x.start_time)
df

Line Item  Revenue  Expenses  Profit Start Date
2017Q1      115904     86544   29360 2016-02-01
2017Q2      120854     89485   31369 2016-05-01
2017Q3      118179     87484   30695 2016-08-01
2017Q4      130936     97743   33193 2016-11-01
2018Q1      117542     87688   29854 2017-02-01

In [62]:
df['End Date'] = df['End Date'].dt.date
df

Line Item  Revenue  Expenses  Profit Start Date    End Date
2017Q1      115904     86544   29360 2016-02-01  2016-04-30
2017Q2      120854     89485   31369 2016-05-01  2016-07-31
2017Q3      118179     87484   30695 2016-08-01  2016-10-31
2017Q4      130936     97743   33193 2016-11-01  2017-01-31
2018Q1      117542     87688   29854 2017-02-01  2017-04-30