In [2]:
import pandas as pd

india_weather = pd.DataFrame ({
    "city": ["Mumbai", "Delhi", "Banglore"],
    "temperature": [32, 45, 36],
    "humidity": [80, 50, 70]
})

india_weather

       city  temperature  humidity
0    Mumbai           32        80
1     Delhi           45        50
2  Banglore           36        70

In [3]:
us_weather = pd.DataFrame ({
    "city": ["New York", "San Francisco", "Los Angeles"],
    "temperature": [28, 32, 30],
    "humidity": [80, 45, 60]
})

us_weather

            city  temperature  humidity
0       New York           28        80
1  San Francisco           32        45
2    Los Angeles           30        60

In [4]:
df = pd.concat([india_weather, us_weather])
df

            city  temperature  humidity
0         Mumbai           32        80
1          Delhi           45        50
2       Banglore           36        70
0       New York           28        80
1  San Francisco           32        45
2    Los Angeles           30        60

In [5]:
df = pd.concat([india_weather, us_weather], ignore_index = True)
df

            city  temperature  humidity
0         Mumbai           32        80
1          Delhi           45        50
2       Banglore           36        70
3       New York           28        80
4  San Francisco           32        45
5    Los Angeles           30        60

In [7]:
df = pd.concat([india_weather, us_weather], keys = ["india", "us"])
df

                  city  temperature  humidity
india 0         Mumbai           32        80
      1          Delhi           45        50
      2       Banglore           36        70
us    0       New York           28        80
      1  San Francisco           32        45
      2    Los Angeles           30        60

In [8]:
df.loc["india"]

       city  temperature  humidity
0    Mumbai           32        80
1     Delhi           45        50
2  Banglore           36        70

In [9]:
df.loc["us"]

            city  temperature  humidity
0       New York           28        80
1  San Francisco           32        45
2    Los Angeles           30        60

In [23]:
temperature_df = pd.DataFrame ({
    "city": ["New York", "San Francisco", "Los Angeles"],
    "temperature": [28, 32, 30],
    
}, index = [0, 1, 2])

temperature_df

            city  temperature
0       New York           28
1  San Francisco           32
2    Los Angeles           30

In [25]:
windspeed_df = pd.DataFrame ({
    "city": ["New York", "San Francisco"],
    "windspeed": [8, 15,],

}, index = [0, 1])

windspeed_df

            city  windspeed
0       New York          8
1  San Francisco         15

In [26]:
df = pd.concat([temperature_df, windspeed_df], axis = 1)
df

            city  temperature           city  windspeed
0       New York           28       New York        8.0
1  San Francisco           32  San Francisco       15.0
2    Los Angeles           30            NaN        NaN

In [27]:
temperature_df

            city  temperature
0       New York           28
1  San Francisco           32
2    Los Angeles           30

In [30]:
s = pd.Series(["Rain", "Sunny", "Dry"], name = "event")
s

0     Rain
1    Sunny
2      Dry
Name: event, dtype: object

In [31]:
df = pd.concat([temperature_df, s], axis = 1)
df

            city  temperature  event
0       New York           28   Rain
1  San Francisco           32  Sunny
2    Los Angeles           30    Dry