In [2]:
import pandas as pd
df = pd.read_excel("stocks.xlsx", header = [0,1], index_col = 0)
df

              Price                  Price to earnings ratio (P/E)         \
Company    Facebook Google Microsoft                      Facebook Google
2017-06-05      155    955        66                         37.10   32.0
2017-06-06      150    987        69                         36.98   31.3
2017-06-07      153    963        62                         36.78   31.7
2017-06-08      155   1000        61                         36.11   31.2
2017-06-09      156   1012        66                         37.07   30.0


Company    Microsoft
2017-06-05     30.31
2017-06-06     30.56
2017-06-07     30.46
2017-06-08     30.11
2017-06-09     31.00

In [5]:
df_stacked = df.stack()
df_stacked

C:\Users\Smoke Nandos\AppData\Local\Temp\ipykernel_24296\4229929500.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_stacked = df.stack()

                      Price  Price to earnings ratio (P/E)
           Company
2017-06-05 Facebook     155                          37.10
           Google       955                          32.00
           Microsoft     66                          30.31
2017-06-06 Facebook     150                          36.98
           Google       987                          31.30
           Microsoft     69                          30.56
2017-06-07 Facebook     153                          36.78
           Google       963                          31.70
           Microsoft     62                          30.46
2017-06-08 Facebook     155                          36.11
           Google      1000                          31.20
           Microsoft     61                          30.11
2017-06-09 Facebook     156                          37.07
           Google      1012                          30.00
           Microsoft     66                          31.00

In [6]:
df_stacked.unstack()

              Price                  Price to earnings ratio (P/E)         \
Company    Facebook Google Microsoft                      Facebook Google
2017-06-05      155    955        66                         37.10   32.0
2017-06-06      150    987        69                         36.98   31.3
2017-06-07      153    963        62                         36.78   31.7
2017-06-08      155   1000        61                         36.11   31.2
2017-06-09      156   1012        66                         37.07   30.0


Company    Microsoft
2017-06-05     30.31
2017-06-06     30.56
2017-06-07     30.46
2017-06-08     30.11
2017-06-09     31.00

In [8]:
df2 = pd.read_excel("stocks_3_levels.xlsx", header= [0,1,2], index_col = 0)
df2

        Price Ratios                                                        \
               Price                  Price to earnings ratio (P/E)
Company     Facebook Google Microsoft                      Facebook Google
Q1 2016          155    955        66                         37.10   32.0
Q2 2016          150    987        69                         36.98   31.3
Q3 2016          153    963        62                         36.78   31.7
Q4 2016          155   1000        61                         36.11   31.2
Q1 2017          156   1012        66                         37.07   30.0

                  Income Statement                                     \
                         Net Sales                  Net Profit
Company Microsoft         Facebook Google Microsoft   Facebook Google
Q1 2016     30.31              2.6     20     18.70       0.80   5.43
Q2 2016     30.56              3.1     22     21.30       0.97   5.89
Q3 2016     30.46              4.3     24     21.45       1.20   6.10
Q4 2016     30.11              6.7     26     21.88       1.67   6.50
Q1 2017     31.00              8.1     31     22.34       2.03   6.40



Company Microsoft
Q1 2016      4.56
Q2 2016      5.10
Q3 2016      5.43
Q4 2016      5.89
Q1 2017      6.09

In [13]:
df2.stack(level = 0)

C:\Users\Smoke Nandos\AppData\Local\Temp\ipykernel_24296\2500371938.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df2.stack(level = 0)

                            Price                    \
Company                  Facebook  Google Microsoft
Q1 2016 Income Statement      NaN     NaN       NaN
        Price Ratios        155.0   955.0      66.0
Q2 2016 Income Statement      NaN     NaN       NaN
        Price Ratios        150.0   987.0      69.0
Q3 2016 Income Statement      NaN     NaN       NaN
        Price Ratios        153.0   963.0      62.0
Q4 2016 Income Statement      NaN     NaN       NaN
        Price Ratios        155.0  1000.0      61.0
Q1 2017 Income Statement      NaN     NaN       NaN
        Price Ratios        156.0  1012.0      66.0

                         Price to earnings ratio (P/E)                   \
Company                                       Facebook Google Microsoft
Q1 2016 Income Statement                           NaN    NaN       NaN
        Price Ratios                             37.10   32.0     30.31
Q2 2016 Income Statement                           NaN    NaN       NaN
        Price Ratios                             36.98   31.3     30.56
Q3 2016 Income Statement                           NaN    NaN       NaN
        Price Ratios                             36.78   31.7     30.46
Q4 2016 Income Statement                           NaN    NaN       NaN
        Price Ratios                             36.11   31.2     30.11
Q1 2017 Income Statement                           NaN    NaN       NaN
        Price Ratios                             37.07   30.0     31.00

                         Net Sales                  Net Profit         \
Company                   Facebook Google Microsoft   Facebook Google
Q1 2016 Income Statement       2.6   20.0     18.70       0.80   5.43
        Price Ratios           NaN    NaN       NaN        NaN    NaN
Q2 2016 Income Statement       3.1   22.0     21.30       0.97   5.89
        Price Ratios           NaN    NaN       NaN        NaN    NaN
Q3 2016 Income Statement       4.3   24.0     21.45       1.20   6.10
        Price Ratios           NaN    NaN       NaN        NaN    NaN
Q4 2016 Income Statement       6.7   26.0     21.88       1.67   6.50
        Price Ratios           NaN    NaN       NaN        NaN    NaN
Q1 2017 Income Statement       8.1   31.0     22.34       2.03   6.40
        Price Ratios           NaN    NaN       NaN        NaN    NaN


Company                  Microsoft
Q1 2016 Income Statement      4.56
        Price Ratios           NaN
Q2 2016 Income Statement      5.10
        Price Ratios           NaN
Q3 2016 Income Statement      5.43
        Price Ratios           NaN
Q4 2016 Income Statement      5.89
        Price Ratios           NaN
Q1 2017 Income Statement      6.09
        Price Ratios           NaN